[[looking_glasses]]
name = "Route Views"
host = "route-views.routeviews.org"
username = "rviews"
template = "cisco"

[[looking_glasses]]
name = "HE Route Server"
host = "route-server.he.net"
password = "rviews"
template = "cisco"

[[looking_glasses]]
name = "IX.br São Paulo"
host = "lg.sp.ptt.br"
template = "cisco"

[[looking_glasses]]
name = "IX.br Rio de Janeiro"
host = "lg.rj.ix.br"
template = "cisco"

[[looking_glasses]]
name = "IX.br Fortaleza"
host = "lg.ce.ix.br"
template = "cisco"

[[looking_glasses]]
name = "AT&T Route Server"
host = "route-server.ip.att.net"
username = "rviews"
password = "rviews"
template = "juniper"

[[looking_glasses]]
name = "GTT Route Server"
host = "route-server.as3257.net"
username = "public"
password = "public"
template = "juniper"

[[looking_glasses]]
name = "DE-CIX"
host = "lg.de-cix.net"
template = "alice"

[[looking_glasses]]
name = "LINX"
host = "alice-rs.linx.net"
template = "alice"

[[looking_glasses]]
name = "JEDIX"
host = "alice-rs-jedix.linx.net"
template = "alice"

[[looking_glasses]]
name = "LINX Collectors"
host = "alice-collector.linx.net"
template = "alice"

[[looking_glasses]]
name = "Netnod"
host = "lg.netnod.se"
template = "alice"

[[looking_glasses]]
name = "NINE IX"
host = "lg.nine-ix.net"
template = "alice"

[[looking_glasses]]
name = "SFMIX"
host = "alice.sfmix.org"
template = "alice"

[[looking_glasses]]
name = "GigaPIX"
host = "glass.gigapix.pt"
template = "alice"

[[looking_glasses]]
name = "IIX Indonesia"
host = "lg.iix.net.id"
template = "alice"

[[looking_glasses]]
name = "DataIX"
host = "lg.dataix.ru"
template = "alice"

[[looking_glasses]]
name = "Digital Realty IX"
host = "lg.ix-access.digitalrealty.com"
template = "alice"

[[looking_glasses]]
name = "GNM-IX"
host = "lg.gnm-ix.net"
template = "alice"
